-- USERS
CREATE TABLE Users (
    UserID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FullName VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    PhoneNumber VARCHAR(15),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ADDRESSES
CREATE TABLE Addresses (
    AddressID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    UserID INTEGER REFERENCES Users(UserID),
    AddressLine VARCHAR(255),
    City VARCHAR(50),
    State VARCHAR(50),
    Pincode VARCHAR(10),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- VENDORS
CREATE TABLE Vendors (
    VendorID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    VendorName VARCHAR(100),
    ContactEmail VARCHAR(100),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- PRODUCT CATEGORIES
CREATE TABLE ProductCategories (
    CategoryID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CategoryName VARCHAR(100) NOT NULL
);

-- PRODUCTS
CREATE TABLE Products (
    ProductID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Description VARCHAR(255),
    CategoryID INTEGER REFERENCES ProductCategories(CategoryID),
    Price DECIMAL(10,2),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- INVENTORY
CREATE TABLE Inventory (
    InventoryID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    VendorID INTEGER REFERENCES Vendors(VendorID),
    ProductID INTEGER REFERENCES Products(ProductID),
    QuantityAvailable INTEGER,
    LastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ORDERS
CREATE TABLE Orders (
    OrderID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    UserID INTEGER REFERENCES Users(UserID),
    VendorID INTEGER REFERENCES Vendors(VendorID),
    OrderDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TotalAmount DECIMAL(10,2)
);

-- ORDER ITEMS
CREATE TABLE OrderItems (
    OrderItemID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    OrderID INTEGER REFERENCES Orders(OrderID),
    ProductID INTEGER REFERENCES Products(ProductID),
    Quantity INTEGER,
    Price DECIMAL(10,2)
);

-- PAYMENTS
CREATE TABLE Payments (
    PaymentID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    OrderID INTEGER REFERENCES Orders(OrderID),
    PaymentMode VARCHAR(50),
    PaymentStatus VARCHAR(50),
    PaidAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- DELIVERY PARTNERS
CREATE TABLE DeliveryPartners (
    PartnerID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FullName VARCHAR(100),
    PhoneNumber VARCHAR(15)
);

-- STATUS
CREATE TABLE Status (
    StatusID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    StatusName VARCHAR(50)
);

-- DELIVERY STATUS
CREATE TABLE DeliveryStatus (
    DeliveryID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    OrderID INTEGER REFERENCES Orders(OrderID),
    StatusID INTEGER REFERENCES Status(StatusID),
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- REVIEWS
CREATE TABLE Reviews (
    ReviewID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    UserID INTEGER REFERENCES Users(UserID),
    ProductID INTEGER REFERENCES Products(ProductID),
    Rating INTEGER CHECK (Rating BETWEEN 1 AND 5),
    Comment VARCHAR(255),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);